### ISSUE TITLE
variable dependent files

### ISSUE THREAD

**Issue by queckezz** [aaronj1335/rework-webpack-loader#3]
This example is currently not working:

**index.css**

``` css
@import './vars.css';

h1 {
  font-size: var(--h1);
}
```

**vars.css**

``` css
:root {
  --h1: 2em;
}
```

It gives me the error that it can't find the given variable `--h1`:

```
ERROR in ./~/rework-webpack-loader!./build/config/npm-css-loader.js!./lib/boot/style.css
Module build failed: Error: rework-vars: variable "--h1" is undefined
    at {path}/node_modules/rework-vars/index.js:114:42
    at String.replace (native)
    at resolveValue ({path}/node_modules/rework-vars/index.js:112:26)
    at {path}/node_modules/rework-vars/index.js:67:25
    at {path}/node_modules/rework-vars/node_modules/rework-visit/index.js:36:5
    at Array.forEach (native)
    at visit ({path}/node_modules/rework-vars/node_modules/rework-visit/index.js:18:14)
    at Object.vars ({path}/node_modules/rework-vars/index.js:53:5)
    at Object.<anonymous> ({path}/node_modules/rework-webpack-loader/index.js:18:26)
    at tryCatchReject ({path}/node_modules/rework-webpack-loader/node_modules/when/lib/makePromise.js:758:30)
 @ ./lib/boot/style.css 4:14-279 12:19-284
```

By reading your readme it seems that this plugin should exactly solve this use case.

**Comment by aaronj1335** [comment]
it should! mind posting your config? or a link to the repo where it fails? admittedly i mostly track down these issues with a debugger where i can actually run the build...

**Comment by queckezz** [comment]
Thanks for the fast response!

This is my current webpack setup:

``` js
var autoprefixer = require('autoprefixer-core')
var webpack = require('webpack')
var join = require('path').join
var conf = require('rc')('app')
var fmt = require('gofmt')()

var customMedia = require('rework-custom-media')
var vars = require('rework-vars')

var public = 'static'

module.exports = {
  devtool: eval,

  entry: [
    fmt('webpack-dev-server/client?http://localhost:%s', conf.dev.port),
    'webpack/hot/only-dev-server',

    './lib/boot/index.js'
  ],

  output: {
    path: join(__dirname, public),
    filename: 'index.js',
    publicPath: fmt('http://localhost:%s/%s/', conf.dev.port, public)
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],

  resolve: {
    extensions: [
      '',
      'index.js',
      '.js',
      '.css',
      'index.css'
    ],

    packageMains: [
      'style',
      'main'
    ]
  },

  resolveLoader: {
    modulesDirectories: [
      'node_modules',
      __dirname
    ]
  },

  module: {
    preLoaders: [
      {
        test: /\.css$/,
        loaders: ['npm-css-loader']
      }
    ],

    loaders: [
      {
        test: /\.js$/,
        loaders: ['react-hot'],
        exclude: /node_modules/
      },

      {
        test: /\.css$/,
        loader: 'style-loader!rework-webpack-loader'
      },
    ]
  },

  rework: {
    use: [
      vars(),
      customMedia()
    ]
  }
}
```

the `npm-css-loader` is currently private and i'm using it to be able to import modules like [basscss](http://www.basscss.com/) or suitcss. Basically it's just rewriting every absolute url from `basscss` to `~basscss`. But i think it shouldn't matter since it doesn't work either way.

Atm, it's just a mess using npm-style css components together with webpack

**Comment by aaronj1335** [comment]
[css vars are tricky](https://github.com/aaronj1335/rework-webpack-loader#why-not-just-chain-plugins-together), and you need to resolve them at the start of your build (and restart the server every time the change :cry:). you can find an example of this in [the readme](https://github.com/aaronj1335/rework-webpack-loader#advanced-configuration-example):

``` js
var reworkLoader = require('rework-webpack-loader');
var reworkVars = require('rework-vars');
var reworkCalc = require('rework-calc');
var reworkCustomMedia = require('rework-custom-media');

var cssVarMap = reworkLoader.makeVarMap('src/index.css');
// ...
module.exports = {
  // ...
  rework: {
    use: [
      reworkLoader.plugins.imports,
      reworkLoader.plugins.urls,
      reworkLoader.plugins.stripLocalDefs(cssVarMap),
      reworkCustomMedia({map: cssVarMap}),
      reworkVars({map: cssVar,Map}),
      reworkCalc
    ]
  }
};
```
